# Generated by Django 3.1.1 on 2020-09-30 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_en', models.CharField(max_length=100, null=True)),
                ('nombre_es', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_en', models.CharField(max_length=100, null=True)),
                ('nombre_es', models.CharField(max_length=100, null=True)),
                ('isla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.isla')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.TextField(max_length=100)),
                ('actividad_en', models.TextField(max_length=100, null=True)),
                ('actividad_es', models.TextField(max_length=100, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], max_length=100)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lugar')),
            ],
        ),
    ]
